# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [main]

defaults:
 run:
  working-directory: /home/runner/work/NutPushover/NutPushover/

jobs:

  main:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        cache: false
        go-version: '1.23.6'

    - name: Build
      run: go build -o upsnotify -v .

    - name: version
      run: echo "RELVER=$(./upsnotify --version)" >> $GITHUB_OUTPUT
      id: version
      
    - name: Create Tag
      uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
          tag: ${{steps.version.outputs.RELVER}}
          tag_exists_error: false
          message: Version ${{steps.version.outputs.RELVER}}
          github_token: ${{ secrets.api_token }}
          
    - name: release
      uses: elgohr/Github-Release-Action@v5
      id: release
      env:
        GH_TOKEN: ${{ secrets.api_token }}
      with:
        title: New Release Version ${{steps.version.outputs.RELVER}}
        tag: $RELVER
      if: ${{ steps.tag_create.outputs.tag_exists == 'false' }}

    - name: upload artifact
      uses: softprops/action-gh-release@v2
      with: 
        files: upsnotify
        token: ${{ secrets.api_token }}
      if: ${{ steps.tag_create.outputs.tag_exists == 'false' }}
